server:
  port: 8080
spring:
  application:
    name: "ms_event_receiver"
  devtools:
    add-properties: false
  main:
    allow-bean-definition-overriding: true
  h2:
    console:
      enabled: true
      path: "/h2"

  profiles:
    include: "local"
  r2dbc:
    pool:
      enabled: true
      max-size: 10
      initial-size: 10
      max-idle-time: 30
entrypoint:
  sqs:
    region: "us-east-1"
    endpoint: "http://localhost:4566"
    queueUrl: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/WebhookQueue"
    waitTimeSeconds: 30
    maxNumberOfMessages: 10
    visibilityTimeout: 5
    numberOfThreads: 1
    visibilityTimeoutSeconds: 10
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "webhook"
    schema: "public"
    username: "user"
    password: "password"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    org.springframework.r2dbc.core: DEBUG