server:
  port: 8081
spring:
  application:
    name: "ms_reports"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  r2dbc:
    pool:
      enabled: true
      max-size: 10
      initial-size: 10
      max-idle-time: 30
adapters:
  r2dbc:
    host: "localhost"
    port: 5432
    database: "webhook"
    schema: "public"
    username: "user"
    password: "password"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080"
logging:
  level:
    org.springframework.r2dbc.core: DEBUG