version: '3.8'

services:
  localstack:
    build:
      context: ../infrastructure
    container_name: localstack
    ports:
      - "4566:4566" 
    networks:
      - mynetwork
  generator:
    build:
      context: ../event_generator 
    environment:
      - AVG_TIME_BETWEEN_EVENTS_MS=1000
      - STD_DV_TIME_BETWEEN_EVENTS_MS=200
      - GITHUB_REPOS_ENABLED=true
      - GITHUB_ACTIONS_ENABLED=true
      - AZURE_REPOS_ENABLED=true
      - AZURE_ACTIONS_ENABLED=true
    container_name: generator
    depends_on:
      - localstack 
    networks:
      - mynetwork
  reports:
    build:
      context: ../ms_reports
      dockerfile: Dockerfile
    container_name: ms_reports
    ports:
      - "8081:8081" 
    depends_on:
      - localstack
      - db
    networks:
      - mynetwork
  
  receiver:
    build:
      context: ../ms_event_receiver
      dockerfile: Dockerfile
    container_name: ms_event_receiver
    ports:
      - "8080:8080" 
    depends_on:
      - localstack
      - db
    networks:
      - mynetwork

  db:
    build:
      context: ../db 
      dockerfile: Dockerfile
    container_name: webhook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
