version: '3.8'

services:
  app:
    build:
      context: ../ms_reports
      dockerfile: Dockerfile
    container_name: ms_reports
    ports:
      - "8081:8081" 
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    build:
      context: ../db 
      dockerfile: Dockerfile
    container_name: webhook_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mynetwork

volumes:
  postgres-data:

networks:
  mynetwork:
    driver: bridge
